window.PROPERTIES = [
  {
    slug: "it-park-condo",
    offer: "sale",
    offerLabel: "For Sale",
    type: "condo",
    typeLabel: "Condominium",
    title: "2BR Condo in IT Park",
    price: 7800000,
    location: "Lahug, Cebu City",
    specs: "58 sqm | 2 Bed | 1 Bath",
    summary: "Walkable to offices, dining, and transport hubs. Suitable for professionals and investors seeking stable rental demand.",
    searchLocation: "Lahug Cebu City",
    mockLabel: "IT Park View",
    mockTone: "tone-1"
  },
  {
    slug: "banilad-townhouse",
    offer: "sale",
    offerLabel: "For Sale",
    type: "townhouse",
    typeLabel: "Townhouse",
    title: "Modern Townhouse in Banilad",
    price: 11200000,
    location: "Banilad, Cebu City",
    specs: "120 sqm lot | 3 Bed | 2 Bath",
    summary: "Located in a quiet gated pocket with convenient access to schools, malls, and major roads.",
    searchLocation: "Banilad Cebu City",
    mockLabel: "Banilad Lane",
    mockTone: "tone-2"
  },
  {
    slug: "talamban-detached",
    offer: "sale",
    offerLabel: "For Sale",
    type: "house",
    typeLabel: "House",
    title: "Single Detached Home in Talamban",
    price: 15500000,
    location: "Talamban, Cebu City",
    specs: "220 sqm lot | 4 Bed | 3 Bath",
    summary: "Spacious family layout with outdoor area and room for future upgrades.",
    searchLocation: "Talamban Cebu City",
    mockLabel: "Talamban Gardens",
    mockTone: "tone-3"
  },
  {
    slug: "mabolo-ayala-rent",
    offer: "rent",
    offerLabel: "For Rent",
    type: "condo",
    typeLabel: "Condominium",
    title: "1BR Condo near Ayala",
    price: 38000,
    location: "Mabolo, Cebu City",
    specs: "46 sqm | 1 Bed | 1 Bath",
    summary: "Central rental option with easy access to Ayala Center and nearby business districts.",
    searchLocation: "Mabolo Cebu City",
    mockLabel: "Ayala Skyline",
    mockTone: "tone-4"
  },
  {
    slug: "talisay-lot",
    offer: "sale",
    offerLabel: "For Sale",
    type: "lot",
    typeLabel: "Lot",
    title: "Residential Lot in Talisay",
    price: 6200000,
    location: "Talisay, Cebu",
    specs: "310 sqm lot | Corner parcel",
    summary: "Good lot option for custom-home buyers looking for long-term value.",
    searchLocation: "Talisay Cebu",
    mockLabel: "Talisay Parcel",
    mockTone: "tone-5"
  },
  {
    slug: "mactan-family-rent",
    offer: "rent",
    offerLabel: "For Rent",
    type: "house",
    typeLabel: "House",
    title: "Family House near Mactan Newtown",
    price: 55000,
    location: "Lapu-Lapu, Cebu",
    specs: "180 sqm lot | 3 Bed | 2 Bath",
    summary: "Well-positioned for airport access and island-side lifestyle amenities.",
    searchLocation: "Lapu-Lapu Cebu",
    mockLabel: "Mactan Breeze",
    mockTone: "tone-6"
  }
];
